version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch
