spring:
  activemq:
    in-memory: false
    broker-url: tcp://host.docker.internal:61616
    user: admin
    password: admin
  mail:
    host: host.docker.internal
    port: 1025

activemq:
  destination: email

email:
  from: awesome@testing.com

server:
  port: 4002
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: "*"